---
- name: mine
  hosts: all
  user: ubuntu
  pre_tasks:
    - name: "update apt packages."
      become: true
      apt:
        update_cache: true
      changed_when: False
      when: ansible_distribution == 'Ubuntu'

    - name: "upgrade packages"
      become: true
      apt:
        name: "*"
        state: latest
      when: ansible_distribution == 'Ubuntu'

  roles:
    - setup
